Repository JaeGuipi/travelmaker, pull requests merged in 2024-12, with the labels that each got.

#80 Feat: 마이페이지 추가 및 헤더, 로그인 수정
  public/icons/btn_pen.svg
  src/actions/auth.action.ts
  src/app/(usercard)/layout.tsx
  src/app/(usercard)/my-info/page.tsx
  src/app/ClientPathname.tsx
  src/app/layout.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/MyPageForm.module.scss
  src/components/Auth/MyPageForm.tsx
  src/components/Button/FormButton.module.scss
  src/components/Input/CustomInput.module.scss
  src/components/Input/CustomInput.tsx
  src/components/Input/FileInput.module.scss
  src/components/Input/FileInput.tsx
  src/components/Layout/ClientPathname.tsx
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/User.tsx
  src/components/UserTab/UserTab.module.scss
  src/components/UserTab/UserTab.tsx
  src/components/UserTab/UserTabList.module.scss
  src/components/UserTab/UserTabList.tsx
  src/lib/api/user.ts
  src/lib/toastMessage.ts
  src/schema/zodSchema.ts
  src/styles/_reset.scss
  src/styles/_variables.scss
  src/types/users/usersTypes.ts
Labels: ✨ Feat

#81 Refactor: 유저 정보 customFetch로 수정 및 공용 레이아웃 스타일 변경
  src/actions/auth.action.ts
  src/app/(usercard)/layout.tsx
  src/app/(usercard)/my-info/page.tsx
  src/components/Auth/MyPageForm.module.scss
  src/components/Auth/MyPageForm.tsx
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Header/Header.tsx
  src/components/UserTab/UserTab.tsx
  src/middleware.ts
  src/styles/_variables.scss
  src/utils/customFetch.ts
Labels: 🔨 Refactor

#84 Feat(76): 예약내역페이지 제작
  public/images/no-list.png
  src/actions/auth.action.ts
  src/app/(auth)/signup/page.tsx
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-reservation/page.module.scss
  src/app/(usercard)/my-reservation/page.tsx
  src/app/api/my-reservations/[id]/route.ts
  src/app/api/my-reservations/route.ts
  src/components/Auth/SignUpForm.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/ItemLayout/ItemLayout.module.scss
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Layout/Footer/Footer.module.scss
  src/components/Modal/ModalComponents/ConfirmModal.tsx
  src/components/Modal/ModalContainer.module.scss
  src/components/MyReservationItem/MyReservationItem.module.scss
  src/components/MyReservationItem/MyReservationItem.tsx
  src/components/MyReservationList/MyReservationList.module.scss
  src/components/MyReservationList/MyReservationList.tsx
  src/lib/api/myreservation.ts
  src/lib/api/user.ts
  src/utils/getStatusText.ts
Labels: ✨ Feat

#86 Fix: 마이페이지 및 유저 탭 이미지 오류 수정
  src/actions/auth.action.ts
  src/components/Auth/MyPageForm.tsx
  src/components/Input/FileInput.tsx
  src/schema/zodSchema.ts
Labels: 🐞 Fix

#87 fix(76): dropdown list로 수정
  src/components/MyReservationList/MyReservationList.tsx
Labels: 🐞 Fix

#90 feat(89): loading spinner 제작
  public/gif/loading.gif
  src/components/LoadingSpinner/LoadingSpinner.module.scss
  src/components/LoadingSpinner/LoadingSpinner.tsx
Labels: ✨ Feat

#93 Feat: 검색 페이지 제작
  next.config.mjs
  package-lock.json
  src/app/layout.tsx
  src/app/search-page/SearchResults.module.scss
  src/app/search-page/SearchResults.tsx
  src/app/search-page/page.module.scss
  src/app/search-page/page.tsx
  src/components/BottomBar/BottomBar.module.scss
  src/components/BottomBar/BottomBar.tsx
  src/components/Input/CustomInput.tsx
  src/components/Layout/Header/Header.tsx
  src/components/SearchBar.tsx
  src/lib/api/activities.ts
Labels: ✨ Feat

#94 Feat: 체험 상세 캘린더 구현
  package-lock.json
  package.json
  public/icons/calendar_next.svg
  public/icons/calendar_prev.svg
  public/icons/icon_mark.svg
  src/app/activities/[id]/page.module.scss
  src/app/activities/[id]/page.tsx
  src/app/api/activities/[activityId]/reservations/route.ts
  src/components/Activity/ActivityDetail/ActivityDetail.module.scss
  src/components/Activity/ActivityDetail/ActivityDetail.tsx
  src/components/Activity/DetailSubImg.tsx
  src/components/Activity/Review/ReviewList.module.scss
  src/components/Activity/Review/ReviewList.tsx
  src/components/Activity/Schedules/ScheduleDetail/ScheduleDetail.module.scss
  src/components/Activity/Schedules/ScheduleDetail/ScheduleDetail.tsx
  src/components/Activity/Schedules/ScheduleDetail/components/Calendar.module.scss
  src/components/Activity/Schedules/ScheduleDetail/components/Calendar.tsx
  src/components/Activity/Schedules/ScheduleDetail/components/CalendarStyle.scss
  src/components/Activity/Schedules/ScheduleDetail/components/HeadCountSelector.module.scss
  src/components/Activity/Schedules/ScheduleDetail/components/HeadCountSelector.tsx
  src/components/Activity/Schedules/ScheduleDetail/components/TotalPrice.module.scss
  src/components/Activity/Schedules/ScheduleDetail/components/TotalPrice.tsx
  src/components/Activity/Schedules/Schedules.module.scss
  src/components/Activity/Schedules/Schedules.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Home/ActivityListSection/CategoryList.tsx
  src/components/Modal/ModalComponents/FormInfoModal.tsx
  src/components/Modal/ModalComponents/ModalStyle.module.scss
  src/components/Modal/ModalContainer.module.scss
  src/lib/api/activities.ts
  src/lib/toastMessage.ts
  src/styles/globals.scss
  src/types/activites/activitesTypes.ts
  src/types/types.ts
Labels: ✨ Feat

#97 fix(76): 반응형, 오타, 숫자 표기 수정
  next.config.mjs
  src/app/(usercard)/my-reservation/page.module.scss
  src/app/(usercard)/my-reservation/page.tsx
  src/components/ItemLayout/ItemLayout.module.scss
  src/components/ItemLayout/ItemLayout.tsx
  src/components/MyReservationItem/MyReservationItem.module.scss
  src/components/MyReservationItem/MyReservationItem.tsx
  src/components/MyReservationList/MyReservationList.module.scss
  src/components/MyReservationList/MyReservationList.tsx
Labels: 🐞 Fix

#98 Refactor: 모달 수정
  src/components/Activity/Schedules/ScheduleDetail/ScheduleDetail.tsx
  src/components/Modal/ModalComponents/ConfirmModal.tsx
  src/components/Modal/ModalComponents/FormInfoModal.tsx
  src/components/Modal/ModalComponents/PopupModal.tsx
  src/store/useModalStore.ts
Labels: 🔨 Refactor

#102 Feat: 내 체험 등록 페이지 추가
  src/actions/activity.action.ts
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-activities/register-activity/page.tsx
  src/components/Activity/ActivityForm.module.scss
  src/components/Activity/ActivityForm.tsx
  src/components/Auth/MyPageForm.module.scss
  src/components/Auth/MyPageForm.tsx
  src/components/Dropdown/CategoryDropdown.module.scss
  src/components/Dropdown/CategoryDropdown.tsx
  src/components/Input/BannerInput.module.scss
  src/components/Input/BannerInput.tsx
  src/components/Input/CustomInput.module.scss
  src/components/Input/CustomInput.tsx
  src/components/Input/FileInput.tsx
  src/components/Input/ScheduleInput.module.scss
  src/components/Input/ScheduleInput.tsx
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Header/User.tsx
  src/components/UserTab/UserTab.module.scss
  src/components/UserTab/UserTabList.tsx
  src/hooks/useToast.ts
  src/lib/toastMessage.ts
  src/types/activites/activitesTypes.ts
Labels: ✨ Feat

#99 Feat : 체험 상세페이지 후기 작업
  public/icons/category/cate_all.gif
  public/icons/category/cate_bus.gif
  public/icons/category/cate_culture.gif
  public/icons/category/cate_food.gif
  public/icons/category/cate_sports.gif
  public/icons/category/cate_tour.gif
  public/icons/category/cate_wellbeing.gif
  src/app/activities/[id]/page.module.scss
  src/app/activities/[id]/page.tsx
  src/components/Activity/ActivityDetail/ActivityDetail.module.scss
  src/components/Activity/ActivityDetail/ActivityDetail.tsx
  src/components/Activity/DetailSubImg.module.scss
  src/components/Activity/DetailSubImg.tsx
  src/components/Activity/Review/ReviewList.module.scss
  src/components/Activity/Review/ReviewList.tsx
  src/components/Activity/Schedules/Schedules.module.scss
  src/components/Activity/Schedules/Schedules.tsx
  src/components/Layout/Footer/Footer.module.scss
Labels: ✨ Feat

#101 Feat: 카카오맵 기능 추가
  src/components/Activity/ActivityDetail/ActivityDetail.module.scss
  src/components/Activity/ActivityDetail/ActivityDetail.tsx
  src/components/Activity/ActivityDetail/MapInfo.module.scss
  src/components/Activity/ActivityDetail/MapInfo.tsx
Labels: ✨ Feat

#104 feat(88): 예약내역리스트 후기작성모달
  src/actions/myReservation.ts
  src/components/Activity/Review/ReviewList.module.css
  src/components/Activity/Review/ReviewList.module.css.map
  src/components/Dropdown/Dropdown.module.scss
  src/components/ItemLayout/ItemLayout.module.scss
  src/components/LoadingSpinner/LoadingSpinner.module.css
  src/components/LoadingSpinner/LoadingSpinner.module.css.map
  src/components/Modal/ModalComponents/ConfirmModal.tsx
  src/components/Modal/ModalComponents/FormInfoModal.tsx
  src/components/Modal/ModalComponents/ModalStyle.module.scss
  src/components/Modal/ModalContainer.module.scss
  src/components/MyReservationItem/MyReservationItem.module.scss
  src/components/MyReservationItem/MyReservationItem.tsx
  src/components/MyReservationList/MyReservationList.tsx
  src/lib/toastMessage.ts
  src/styles/globals.css
  src/styles/globals.css.map
Labels: 🔨 Refactor

#106 Feat: 체험 수정 페이지 추가
  src/actions/activity.action.ts
  src/app/(usercard)/my-activities/[activityId]/page.tsx
  src/app/(usercard)/my-activities/register/page.tsx
  src/components/Activity/ActivityForm.tsx
  src/components/Button/FormButton.module.scss
  src/components/Input/CustomInput.module.scss
  src/components/Input/CustomInput.tsx
  src/components/Input/ScheduleInput.tsx
  src/components/LoadingSpinner/LoadingSpinner.module.scss
  src/lib/toastMessage.ts
  src/types/activites/activitesTypes.ts
Labels: ✨ Feat

#107 Refactor : 메인 페이지 & 체험 상세
  src/app/activities/[id]/page.tsx
  src/components/Activity/DetailSubImg.module.scss
  src/components/Activity/DetailSubImg.tsx
  src/components/Activity/DetailSubImgSwiper.module.scss
  src/components/Activity/DetailSubImgSwiper.tsx
  src/components/Activity/Review/ReviewList.tsx
  src/components/Activity/Schedules/ScheduleDetail/ScheduleDetail.tsx
  src/components/Activity/Schedules/ScheduleDetail/components/Calendar.tsx
  src/components/Activity/Schedules/Schedules.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Home/ActivityListSection/ActivityList.tsx
  src/components/Home/ActivityListSection/AllItemList.module.scss
  src/components/Home/ActivityListSection/AllItemList.tsx
  src/components/Home/PopularSection/PopularItemList.tsx
  src/components/Home/PopularSection/PopularItemSwiper.module.scss
  src/lib/api/activities.ts
Labels: 🔨 Refactor

#109 fix(76): 등록한 체험이 없을 때 드롭다운 보여주기
  src/app/(usercard)/my-activities/MyActivityItem/MyActivitiItem.module.scss
  src/app/(usercard)/my-activities/MyActivityItem/MyActivityItem.tsx
  src/app/(usercard)/my-activities/MyActivityList/MyActivityList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.module.scss
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/NoList.module.scss
  src/app/(usercard)/my-reservation/MyReservationList/NoList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/ReviewContent.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Modal/ModalComponents/FormInfoModal.tsx
  src/hooks/useToast.ts
Labels: 🐞 Fix

#111 Feature: 체험 등록, 수정 주소 검색 연결
  package-lock.json
  package.json
  src/actions/activity.action.ts
  src/app/(usercard)/my-activities/MyActivityList/MyActivityList.tsx
  src/app/(usercard)/my-activities/[activityId]/page.tsx
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-activities/register/page.tsx
  src/app/(usercard)/my-info/page.tsx
  src/app/(usercard)/my-reservation/page.tsx
  src/app/activities/[id]/page.tsx
  src/components/Activity/ActivityForm/ActivityForm.module.scss
  src/components/Activity/ActivityForm/ActivityForm.tsx
  src/components/Dropdown/CategoryDropdown.module.scss
  src/components/Dropdown/CategoryDropdown.tsx
  src/components/Input/AddressInput.module.scss
  src/components/Input/AddressInput.tsx
  src/components/Input/ScheduleInput.module.scss
  src/components/Input/ScheduleInput.tsx
  src/components/Layout/Header/Header.tsx
  src/components/UserTab/UserTab.tsx
  src/lib/toastMessage.ts
  src/schema/zodSchema.ts
Labels: ✨ Feat

#119 rename(76) : 예약 내역 페이지 후기 작성 모달 스타일 파일 생성
  src/app/(usercard)/my-reservation/MyReservationItem/MyReservationItem.tsx
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/ReviewContent.module.scss
  src/app/(usercard)/my-reservation/MyReservationList/ReviewContent.tsx
  src/components/Modal/ModalComponents/ModalStyle.module.scss
Labels: 📦️ Chore

#118 Feat: 헤더 유저 탭 메뉴 UI 수정
  src/actions/activity.action.ts
  src/actions/auth.action.ts
  src/app/(usercard)/my-activities/[activityId]/page.tsx
  src/app/(usercard)/my-reservation/ItemTitleLayout/ItemTitleLayout.module.scss
  src/components/Activity/ActivityForm/ActivityForm.module.scss
  src/components/Activity/ActivityForm/ActivityForm.tsx
  src/components/Auth/MyPageForm.module.scss
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Input/FileInput.module.scss
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Header/User.tsx
  src/components/UserTab/UserTab.module.scss
  src/components/UserTab/UserTabList.module.scss
  src/components/UserTab/UserTabList.tsx
Labels: 🔨 Refactor

#120 Feat(113): 예약 현황 사이트 제작
  src/actions/reservation.action.ts
  src/app/(usercard)/reservation-status/Calendar.scss
  src/app/(usercard)/reservation-status/CalendarView.module.scss
  src/app/(usercard)/reservation-status/CalendarView.tsx
  src/app/(usercard)/reservation-status/ReservationModal.module.scss
  src/app/(usercard)/reservation-status/ReservationModal.tsx
  src/app/(usercard)/reservation-status/ReservationStatusDetail.module.scss
  src/app/(usercard)/reservation-status/ReservationStatusDetail.tsx
  src/app/(usercard)/reservation-status/ReservationTItle.tsx
  src/app/(usercard)/reservation-status/ReservationTitle.module.scss
  src/app/(usercard)/reservation-status/page.tsx
  src/app/api/my-activities/reservations/route.ts
  src/app/api/my-activities/reserved-schedule/route.ts
  src/components/Modal/ModalTabs.module.scss
  src/components/Modal/ModalTabs.tsx
  src/middleware.ts
  src/types/myActivitiesTypes/myActivitiesTypes.ts
Labels: ✨ Feat

#123 Refactor(110) : types 폴더로 경로 변경 및 스크롤 mixin 생성
  src/app/(usercard)/my-activities/MyActivityItem/MyActivityItem.tsx
  src/app/(usercard)/my-activities/MyActivityList/MyActivityList.tsx
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-reservation/MyReservationItem/MyReservationItem.tsx
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/ReviewContent.tsx
  src/app/(usercard)/my-reservation/page.tsx
  src/app/api/my-notifications/route.ts
  src/components/Layout/Header/Notification/Notification.module.scss
  src/styles/_mixins.scss
  src/styles/globals.scss
  src/types/myReservationsTypes/myReservationsTypes.ts
  src/types/types.ts
Labels: 🔨 Refactor

#116 Refactor: 체험 상세 캘린더
  src/components/Activity/DetailSubImg.tsx
  src/components/Activity/DetailSubImgSwiper.module.scss
  src/components/Activity/DetailSubImgSwiper.tsx
  src/components/Activity/Review/ReviewList.tsx
  src/components/Activity/Schedules/ScheduleDetail/ScheduleDetail.module.scss
  src/components/Activity/Schedules/ScheduleDetail/ScheduleDetail.tsx
  src/components/Activity/Schedules/ScheduleDetail/components/Calendar.module.scss
  src/components/Activity/Schedules/ScheduleDetail/components/Calendar.tsx
  src/components/Activity/Schedules/ScheduleDetail/components/CalendarStyle.scss
  src/components/Alarm/Alarm.module.scss
  src/components/Alarm/Alarm.tsx
  src/components/BottomBar/BottomBar.module.scss
  src/components/BottomBar/BottomBar.tsx
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/Notification/Notification.module.scss
  src/components/Layout/Header/User.tsx
  src/components/Modal/ModalComponents/ModalStyle.module.scss
Labels: 🔨 Refactor

#124 Build: 빌드 시 유저 데이터 에러 수정
  src/app/(usercard)/my-info/page.tsx
  src/app/activities/[id]/page.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Input/FileInput.tsx
  src/components/Layout/Header/Header.tsx
  src/components/UserTab/UserTab.tsx
Labels: ⚙ Build, 🐞 Fix

#128 Refactor(88) : 알림 없을 때 UI 구현 및 소셜 로그인 컴포넌트 suspense로 감싸기
  package-lock.json
  package.json
  src/components/Alarm/Alarm.tsx
  src/components/Layout/Header/Notification/Notification.module.scss
  src/components/Layout/Header/Notification/Notification.tsx
  src/styles/globals.css
  src/styles/globals.css.map
Labels: 🔨 Refactor

#134 Chore: 로고 오타 수정 및 FormButton 수정
  public/images/logo-column.svg
  public/images/logo.svg
  src/app/(usercard)/my-activities/MyActivityItem/MyActivitiItem.module.scss
  src/app/(usercard)/my-reservation/ItemLayout/ItemLayout.module.scss
  src/app/(usercard)/my-reservation/MyReservationItem/MyReservationItem.module.scss
  src/app/(usercard)/my-reservation/MyReservationItem/MyReservationItem.tsx
  src/components/Button/FormButton.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Input/AddressInput.module.scss
Labels: 📦️ Chore, 🎨 Style

#135 Refactor: 메인 페이지(디자인)
  global.d.ts
  public/images/no_image.png
  public/images/tb_main_bnr01.jpg
  public/images/tb_main_bnr02.jpg
  public/images/tb_main_bnr03.jpg
  src/components/Activity/ActivityDetail/MapInfo.tsx
  src/components/Home/ActivityListSection/AllItemList.module.scss
  src/components/Home/ActivityListSection/AllItemList.tsx
  src/components/Home/ActivityListSection/CategoryList.module.scss
  src/components/Home/PopularSection/PopularItem.tsx
  src/components/Home/PopularSection/PopularItemSwiper.module.scss
  src/components/Home/VisualSection/MainSwiper.tsx
  src/global.d.ts
Labels: 🔨 Refactor, 🎨 Style

#136 Refactor(76): 내 체험 삭제하기 버튼 모달로 수정 및 내 예약 드롭다운 전체 예약 추가
  src/app/(usercard)/my-activities/MyActivityItem/MyActivityItem.tsx
  src/app/(usercard)/my-activities/MyActivityList/MyActivityList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
  src/components/Modal/ModalComponents/ConfirmModal.tsx
Labels: 🔨 Refactor

#141 BASE_URL 등록 및 gitignore 파일 수정
  .gitignore
  src/app/api/google-auth/route.ts
  src/app/api/kakao-auth/route.ts
  src/components/Auth/SocialLoginAndSignup/SocialLoginAndSignup.tsx
Labels: 📦️ Chore, 🔨 Refactor

#142 Refactor(139): 하단바링크연결등리팩토링리스트작업
  README.md
  src/components/BottomBar/BottomBar.module.scss
  src/components/BottomBar/BottomBar.tsx
Labels: 🔨 Refactor

#143 Refactor(139) : not-found page 제작
  src/app/(auth)/signup/page.tsx
  src/app/(usercard)/my-activities/MyActivityItem/MyActivityItem.tsx
  src/app/(usercard)/my-reservation/MyReservationItem/MyReservationItem.tsx
  src/app/not-found.tsx
  src/components/Layout/Header/Notification/Notification.module.scss
  src/components/Layout/Header/Notification/Notification.tsx
  src/components/Modal/ModalComponents/ConfirmModal.tsx
  src/styles/globals.scss
  src/utils/getStatusText.ts
  src/utils/timeDiff.ts
Labels: 🔨 Refactor

#147 refactor : 체험 상세 페이지
  src/app/activities/[id]/page.tsx
  src/components/Activity/ActivityDetail/ActivityDetail.tsx
  src/components/Activity/ActivityDetail/MapInfo.tsx
  src/components/Activity/DetailSubImg.module.scss
  src/components/Activity/DetailSubImg.tsx
  src/components/Activity/Review/ReviewList.module.scss
  src/components/Activity/Review/ReviewList.tsx
  src/components/Activity/Schedules/Schedules.module.scss
  src/components/Activity/Schedules/Schedules.tsx
  src/components/Home/ActivityListSection/AllItemList.tsx
  src/components/Home/PopularSection/PopularItem.tsx
  src/components/Modal/ModalComponents/ConfirmModal.tsx
Labels: 🔨 Refactor

#149 Chore(145): 예약현황 페이지 UI 추가 디자인 및
  src/app/(usercard)/my-reservation/ItemTitleLayout/ItemTitleLayout.tsx
  src/app/(usercard)/reservation-status/CalendarView.tsx
  src/app/(usercard)/reservation-status/page.module.scss
  src/app/(usercard)/reservation-status/page.tsx
  src/app/search-page/SearchResults.module.scss
  src/app/search-page/SearchResults.tsx
  src/app/search-page/page.tsx
  src/components/Input/CustomInput.tsx
  src/lib/auth.ts
  src/middleware.ts
Labels: 📦️ Chore

#152 Refactor(139) : 리팩토링
  src/app/(auth)/signup/page.tsx
  src/app/(usercard)/my-activities/MyActivityItem/MyActivitiItem.module.scss
  src/app/(usercard)/my-activities/MyActivityItem/MyActivityItem.tsx
  src/app/(usercard)/my-activities/MyActivityList/MyActivityList.tsx
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-reservation/MyReservationItem/MyReservationItem.module.scss
  src/app/(usercard)/my-reservation/MyReservationItem/MyReservationItem.tsx
  src/app/(usercard)/my-reservation/page.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/BottomBar/BottomBar.tsx
  src/components/Input/CustomInput.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/Notification/Notification.tsx
  src/middleware.ts
  src/styles/globals.scss
  src/types/types.ts
Labels: 🔨 Refactor

#154 Chore: 미들웨어 로직 수정
  src/app/(usercard)/reservation-status/Calendar.scss
  src/app/(usercard)/reservation-status/page.module.scss
  src/lib/api/activities.ts
  src/lib/auth-handlers.ts
  src/middleware.ts
Labels: 📦️ Chore

#157 refactor : 체험 상세 페이
  src/app/activities/[id]/page.module.scss
  src/app/activities/[id]/page.tsx
  src/components/Activity/ActivityDetail/ActivityDetail.module.scss
  src/components/Activity/ActivityDetail/MapInfo.tsx
  src/components/Activity/DetailSubImg.tsx
  src/components/Activity/Review/ReviewList.tsx
  src/components/Activity/Schedules/Schedules.module.scss
Labels: 🔨 Refactor

#158 Update README.md
  README.md
Labels: 📦️ Chore, 🐞 Fix

#160 Chore(159) : 후기 작성 모달 z-index 수정 및 케밥 버튼 크기 조정
  public/opengraph-image.png
  src/app/(usercard)/my-activities/MyActivityItem/MyActivitiItem.module.scss
  src/app/layout.tsx
  src/components/Alarm/Alarm.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Modal/ModalContainer.module.scss
Labels: 📦️ Chore

#161 Chore: 헤더, not-found 리디렉트 및 유저 이미지 수정
  src/app/(usercard)/layout.tsx
  src/app/(usercard)/my-activities/MyActivityItem/MyActivitiItem.module.scss
  src/app/(usercard)/my-activities/[activityId]/page.tsx
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-reservation/ItemLayout/ItemLayout.module.scss
  src/app/(usercard)/reservation-status/CalendarView.module.scss
  src/app/not-found.tsx
  src/app/search-page/page.tsx
  src/components/Activity/ActivityForm/ActivityForm.module.scss
  src/components/Activity/ActivityForm/ActivityForm.tsx
  src/components/Activity/ActivityForm/components/AddressInput.module.scss
  src/components/Activity/ActivityForm/components/AddressInput.tsx
  src/components/Activity/ActivityForm/components/BannerInput.module.scss
  src/components/Activity/ActivityForm/components/BannerInput.tsx
  src/components/Activity/ActivityForm/components/CategoryDropdown.module.scss
  src/components/Activity/ActivityForm/components/CategoryDropdown.tsx
  src/components/Activity/ActivityForm/components/ScheduleCalendar.scss
  src/components/Activity/ActivityForm/components/ScheduleInput.module.scss
  src/components/Activity/ActivityForm/components/ScheduleInput.tsx
  src/components/Auth/MyPageForm/MyPageForm.module.scss
  src/components/Auth/MyPageForm/MyPageForm.tsx
  src/components/Auth/MyPageForm/components/FileInput.module.scss
  src/components/Auth/MyPageForm/components/FileInput.tsx
  src/components/BottomBar/BottomBar.module.scss
  src/components/Layout/Footer/Footer.module.scss
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/SearchBar.tsx
  src/components/Layout/UserTab/UserTab.module.scss
  src/components/Layout/UserTab/UserTab.tsx
  src/components/Layout/UserTab/UserTabList.module.scss
  src/components/Layout/UserTab/UserTabList.tsx
  src/components/LoadingSpinner/LoadingSpinner.module.scss
  src/styles/_variables.scss
  src/styles/globals.scss
Labels: 📦️ Chore, 🎨 Style

#163 Design : 상세 css 수정
  src/app/activities/[id]/page.module.scss
Labels: 🎨 Style

#164 Chore(159) : image 파일 이름 언더바 -> 대시로 수정
  src/app/layout.tsx
Labels: 📦️ Chore

#165 Design: 메인 페이지 css 수정
  src/components/Home/ActivityListSection/ActivityList.module.scss
  src/components/Home/ActivityListSection/ActivityList.tsx
  src/components/Home/ActivityListSection/AllItemList.module.scss
  src/components/Home/ActivityListSection/CategoryList.module.scss
  src/components/Home/PopularSection/PopularItem.module.scss
  src/components/Home/PopularSection/PopularItemSwiper.module.scss
Labels: 🎨 Style

#169 Chore: 검색 페이지 UI 수정 및 검색바 로직 변경
  public/images/enter_word.png
  public/images/no_item.png
  src/app/search-page/SearchResults.module.scss
  src/app/search-page/SearchResults.tsx
  src/app/search-page/page.module.scss
  src/app/search-page/page.tsx
  src/components/Home/VisualSection/MainSwiper.tsx
  src/components/Home/VisualSection/SwiperText.tsx
  src/components/Layout/Header/SearchBar.tsx
Labels: 📦️ Chore, 🔨 Refactor

#167 Chore: BottomBar 폰트 사이즈, 유저 디폴트 이미지 추가
  public/images/profile.png
  src/app/layout.tsx
  src/components/Activity/ActivityForm/components/AddressInput.tsx
  src/components/BottomBar/BottomBar.module.scss
  src/components/BottomBar/BottomBar.tsx
  src/lib/toastMessage.ts
  src/styles/_variables.scss
  src/styles/globals.scss
Labels: 📦️ Chore

#170 Update README.md
  README.md
Labels: 📦️ Chore

#171 Chore(159) : page 별 title 추가
  src/app/(usercard)/my-activities/[activityId]/page.tsx
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-activities/register/page.tsx
  src/app/(usercard)/my-info/page.tsx
  src/app/(usercard)/my-reservation/page.tsx
  src/app/(usercard)/reservation-status/page.tsx
  src/app/activities/[id]/page.tsx
  src/app/search-page/page.tsx
Labels: 📦️ Chore

#172 배포 1.3
  README.md
  public/images/enter_word.png
  public/images/logo-column.svg
  public/images/logo.svg
  public/images/no_item.png
  public/images/profile.png
  src/actions/activity.action.ts
  src/app/(usercard)/my-activities/[activityId]/page.tsx
  src/app/(usercard)/my-activities/page.tsx
  src/app/(usercard)/my-activities/register/page.tsx
  src/app/(usercard)/my-info/page.tsx
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.module.scss
  src/app/(usercard)/my-reservation/page.tsx
  src/app/(usercard)/reservation-status/page.tsx
  src/app/activities/[id]/page.module.scss
  src/app/activities/[id]/page.tsx
  src/app/layout.tsx
  src/app/search-page/SearchResults.module.scss
  src/app/search-page/SearchResults.tsx
  src/app/search-page/page.module.scss
  src/app/search-page/page.tsx
  src/components/Activity/ActivityForm/components/AddressInput.tsx
  src/components/BottomBar/BottomBar.module.scss
  src/components/BottomBar/BottomBar.tsx
  src/components/Button/Pagination.module.scss
  src/components/Button/Pagination.tsx
  src/components/Home/ActivityListSection/ActivityList.module.scss
  src/components/Home/ActivityListSection/ActivityList.tsx
  src/components/Home/ActivityListSection/AllItemList.module.scss
  src/components/Home/ActivityListSection/CategoryList.module.scss
  src/components/Home/PopularSection/PopularItem.module.scss
  src/components/Home/PopularSection/PopularItemSwiper.module.scss
  src/components/Home/VisualSection/MainSwiper.tsx
  src/components/Home/VisualSection/SwiperText.tsx
  src/components/Layout/Footer/Footer.module.scss
  src/components/Layout/Header/SearchBar.tsx
  src/lib/toastMessage.ts
  src/styles/_variables.scss
  src/styles/globals.scss
Labels: ⚙ Build

#174 Design: 상세 모바일 별표, 주소영역
  src/components/Activity/DetailSubImg.module.scss
  src/components/Activity/Review/ReviewList.tsx
  src/components/Home/ActivityListSection/ActivityList.module.scss
  src/components/Home/PopularSection/PopularItemSwiper.module.scss
  src/components/Home/PopularSection/PopularItemSwiper.tsx
  src/components/Modal/ModalContainer.module.scss
Labels: 🎨 Style

#179 Feat: 간편 회원가입 랜덤 닉네임 생성
  src/actions/auth.action.ts
  src/app/(usercard)/reservation-status/CalendarView.tsx
  src/app/api/google-auth/route.ts
  src/app/api/kakao-auth/route.ts
  src/app/api/my-activities/route.ts
  src/app/api/my-reservations/route.ts
  src/components/Auth/SocialLoginAndSignup/SocialLoginAndSignup.tsx
  src/middleware.ts
  src/utils/randomNickname.ts
Labels: ✨ Feat

#180 Chore(176): 신청한 예약이 없을 때 문구 변경 및 og img 사이즈 삭제
  public/opengraph-image.jpg
  public/opengraph-image.png
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
  src/app/layout.tsx
Labels: 📦️ Chore

#181 Update README.md
  README.md
Labels: 📦️ Chore

#183 Chore: 리드미 최종 수정
  README.md
  src/app/(usercard)/my-reservation/page.tsx
  src/components/Home/VisualSection/SwiperText.tsx
Labels: 📦️ Chore

#186 Fix: 푸터 svg 오류 해결
  src/components/Layout/Footer/Footer.tsx
Labels: 🐞 Fix

#190 Fix: 배포 환경에서 예약 삭제 토스트 메시지 송출 에러
  README.md
  public/images/opengraph-image.jpg
  src/actions/activity.action.ts
  src/app/layout.tsx
  src/components/Activity/ActivityForm/ActivityForm.tsx
Labels: 🐞 Fix

#193 Update README.md
  README.md
Labels: 📦️ Chore

#194 Update README.md
  README.md
Labels: 📦️ Chore

#195 Fix: 리뷰 모달 수정
  src/actions/myReservation.ts
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/ReviewContent.tsx
  src/app/(usercard)/my-reservation/page.tsx
Labels: 🐞 Fix

#196 배포 1.6
  src/actions/myReservation.ts
  src/app/(usercard)/my-reservation/MyReservationList/MyReservationList.tsx
  src/app/(usercard)/my-reservation/MyReservationList/ReviewContent.tsx
  src/app/(usercard)/my-reservation/page.tsx
Labels: 🐞 Fix
