Repository JaeGuipi/travelmaker, pull requests merged in 2024-11, with the labels that each got.

#11 Feat: global Style 기본 설정
  styles/_mixins.scss
  styles/_reset.scss
  styles/_variables.scss
  styles/globals.scss
Labels: ✨ Feat

#23 Feat: 버튼 공용 컴포넌트 추가
  public/icons/btn_alarm.svg
  public/icons/btn_banner_delete.svg
  public/icons/btn_cancel_black.svg
  public/icons/btn_cancel_gray.svg
  public/icons/btn_kebab.svg
  public/icons/btn_minus_time.svg
  public/icons/btn_plus_time.svg
  public/icons/btn_visibility_off.svg
  public/icons/btn_visibility_on.svg
  src/app/test/page.tsx
  src/components/Button/FormButton.module.scss
  src/components/Button/FormButton.tsx
  src/components/Button/Pagination.module.scss
  src/components/Button/Pagination.tsx
Labels: ✨ Feat

#35 feat(34): 성공/실패/알림 토스트 구현
  src/app/layout.tsx
  src/app/page.tsx
  src/hooks/useToast.ts
Labels: ✨ Feat

#38 Feat: API User 관련 함수 제작 #26
  src/app/types/types.ts
  src/lib/api/user.ts
Labels: ✨ Feat

#39 Feat : 모달 공통 컴포넌트 제작
  package-lock.json
  package.json
  public/icons/btn_check.svg
  src/app/layout.tsx
  src/app/modal-test/page.tsx
  src/app/store/useModalStore.ts
  src/app/styles/_variables.scss
  src/components/Button/FormButton.tsx
  src/components/modal/ModalContainer.module.scss
  src/components/modal/ModalContainer.tsx
  src/components/modal/modal-components/ConfirmModal.tsx
  src/components/modal/modal-components/FormInfoModal.tsx
  src/components/modal/modal-components/ModalStyle.module.scss
  src/components/modal/modal-components/PopupModal.tsx
Labels: ✨ Feat

#41 Feat: API 내 예약 조회 함수, 커스텀 패치 함수 제작
  src/lib/api/myreservation.ts
  src/utils/customFetch.ts
Labels: ✨ Feat

#42 Feat: Header 컴포넌트 추가
  public/icons/btn_alarm.svg
  public/images/logo.png
  public/images/profile.png
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/providers.tsx
  src/app/styles/_reset.scss
  src/app/styles/globals.scss
  src/components/Layout/Header.module.scss
  src/components/Layout/Header.tsx
  src/components/input/CustomInput.module.scss
  src/components/input/CustomInput.tsx
  src/hooks/useAuth.ts
Labels: ✨ Feat

#43 Feat(#20) Activities API 작업
  src/app/page.tsx
  src/app/types/activites/activitesTypes.ts
  src/app/types/types.ts
  src/constants/config.ts
  src/lib/api/activities.ts
  src/lib/api/user.ts
Labels: ✨ Feat

#46 feat(37): myactivities api 제작
  src/app/types/myActivitiesTypes/myActivitiesTypes.ts
  src/app/types/types.ts
  src/lib/api/myActivities.ts
Labels: ✨ Feat

#47 Feat: Auth API 추가
  src/app/page.tsx
  src/app/types/types.ts
  src/lib/api/auth.ts
Labels: ✨ Feat

#49 Feat: MyNotifications API 추가
  src/app/types/notifications/notificationsTypes.ts
  src/app/types/types.ts
  src/lib/api/mynotifications.ts
  src/lib/api/myreservation.ts
Labels: ✨ Feat

#51 Feat: 하단바 제작
  src/app/test/bottombar/page.tsx
  src/app/types/types.ts
  src/components/BottomBar/BottomBar.module.scss
  src/components/BottomBar/BottomBar.tsx
  src/constants/config.ts
  src/lib/api/activities.ts
  src/lib/api/myreservation.ts
  src/lib/api/user.ts
  src/utils/customFetch.ts
Labels: ✨ Feat

#52 Feat: Oauth API 추가
  .env
  src/app/api/oauth/apps/route.ts
  src/app/api/oauth/sign-in/[provider]/route.ts
  src/app/api/oauth/sign-up/[provider]/route.ts
  src/app/types/auth/authTypes.ts
  src/app/types/auth/oauthTypes.ts
  src/app/types/types.ts
  src/app/types/users/usersTypes.ts
  src/lib/api/auth.ts
  src/lib/api/user.ts
Labels: ✨ Feat

#55 Refactor: 폴더 구조 변경
  src/app/modal-test/page.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/modal-components/ConfirmModal.tsx
  src/components/modal/modal-components/FormInfoModal.tsx
  src/components/modal/modal-components/PopupModal.tsx
  src/lib/api/activities.ts
  src/lib/api/auth.ts
  src/lib/api/myActivities.ts
  src/lib/api/mynotifications.ts
  src/lib/api/myreservation.ts
  src/lib/api/user.ts
  src/middleware.ts
  src/store/useModalStore.ts
  src/styles/_mixins.scss
  src/styles/_reset.scss
  src/styles/_variables.scss
  src/styles/globals.scss
  src/types/activites/activitesTypes.ts
  src/types/types.ts
Labels: 🔨 Refactor

#59 Delete .env
  .env
Labels: 📦️ Chore

#58 Feat: 로그인 페이지 추가
  public/images/logo_google.svg
  public/images/logo_kakao.svg
  src/app/(auth)/login/page.tsx
  src/components/Auth/AuthForm/AuthForm.module.scss
  src/components/Auth/AuthForm/AuthForm.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/SocialLogin/SocialLogin.module.scss
  src/components/Auth/SocialLogin/SocialLogin.tsx
  src/components/Input/CustomInput.module.scss
  src/components/Input/CustomInput.tsx
  src/components/Layout/Header.tsx
  src/components/input/CustomInput.tsx
  src/hooks/useAuth.ts
  src/lib/api/auth.ts
  src/lib/api/user.ts
  src/lib/toastMessage.ts
  src/schema/zodSchema.ts
  src/styles/_mixins.scss
Labels: ✨ Feat

#65 Feat(48): 회원가입페이지 제작
  .gitignore
  public/images/logo_google.png
  public/images/logo_kakao.png
  src/app/(auth)/signup/page.tsx
  src/app/schema/zodSchema.ts
  src/components/Auth/LoginForm.tsx
  src/components/Input/CustomInput.module.scss
  src/components/input/CustomInput.tsx
  src/components/signUpForm/SignUpForm.module.scss
  src/components/signUpForm/SignUpForm.tsx
  src/components/socialLogin/socialLogin.module.scss
  src/components/socialLogin/socialLogin.tsx
  src/hooks/useToast.ts
  src/lib/api/user.ts
Labels: ✨ Feat

#66 Feat(62): 푸터 제작
  public/icons/ft_facebook.svg
  public/icons/ft_instagram.svg
  public/icons/ft_twitter.svg
  public/icons/ft_youtube.svg
  src/app/layout.tsx
  src/components/Layout/Footer.module.scss
  src/components/Layout/Footer.tsx
Labels: ✨ Feat

#69 Feat(67): 알림 UI 구현
  src/components/Input/CustomInput.module.scss
  src/components/Notification/Notification.module.scss
  src/components/Notification/Notification.tsx
  src/components/input/CustomInput.module.scss
  src/utils/timeDiff.ts
Labels: ✨ Feat
